<footer id="footer">
	<div class="footer-inner">
		<div class="f-left-cont">
			<p class="f_logo"><img src="https://www.srixon.co.kr/images/logo.png" alt="Srixon"></p>
			<div class="f-left-new-block">
				<address>서울특별시 서초구 사평대로 76 로지트 빌딩1층</address>
				<p>대표번호 : 02.3462.3960</p>
				<p>사업자번호 : 220-88-12409</p>
				<p>개인정보책임관리자 : 김재윤 팀장</p>
			</div>
			<ul>
				<li><a href="http://www.srixon.co.kr/util/brand.do">INTRODUCE</a></li>
				<li><a href="http://www.srixon.co.kr/util/catalog.do">CATALOGUE</a></li>
				<li><a href="http://www.srixon.co.kr/util/terms.do">이용약관</a></li>
				<li><a href="http://www.srixon.co.kr/util/personal.do">개인정보취급방침</a></li>
			</ul>
			<p class="copy">COPYRIGHT &copy; BY DUNLOP SPORTS KOREA.<br>ALL RIGHTS RESERVED.</p>
		</div>
		<!--// f-left -->
		<div class="f-right-cont">
			<div class="f-right m-f-left">
				<div class="cont-block">
					<h3>SRIXON</h3>
					<ul>
						<li><a href="http://www.srixon.co.kr/item/balls/list.do?im_num=12">BALLS</a></li>
						<li><a href="http://www.srixon.co.kr/item/clubs/list.do?im_num=8">CLUBS</a></li>
						<li><a href="http://www.srixon.co.kr/item/accessories/main.do">ACCESSORIES</a></li>
						<li><a href="http://www.srixon.co.kr/tour/playerList.do?sp_tour=PGA">TOUR</a></li>
						<li><a href="http://www.srixon.co.kr/experience/performance.do">EXPERIENCE</a></li>
						<li><a href="http://www.srixon.co.kr/news/newsList.do">NEWS&amp;EVENT</a></li>
						<li><a href="http://www.srixon.co.kr/cs/as_reception.do">C/S</a></li>
					</ul>
				</div>
			</div>
			<!--// f-right-cont -->
			<div class="f-right m-f-left" style="position:relative; padding-bottom:80px;">
				<div class="cont-block">
					<h3>CUSTOMER SERVICE</h3>
					<p>02.3462.3960</p>
					<!-- <p><a href="mailto:srixonsportskorea@gmail.com">srixonsportskorea@gmail.com</a></p> -->
				</div>
				<h3 class="m-ver"><a href="http://www.srixon.co.kr/util/brand.do">INTRODUCE</a></h3>
				<h3 class="m-ver"><a href="http://www.srixon.co.kr/util/catalog.do">CATALOGUE</a></h3>
				<div class="foot_sns">
					<h3 class="space">FOLLOW US</h3>
					<ul class="f-sns">
						<li><a href="https://www.facebook.com/Srixonkorea/" target="_blank">facebook</a></li>
						<li><a href="https://www.instagram.com/srixon_korea/" target="_blank">instagram</a></li>
						<li><a href="https://www.youtube.com/channel/UCqTO4tAGtAyRjLQcPm7Wb7A?nohtml5=False"
								target="_blank">youtube</a></li>
					</ul>
				</div>
			</div>
			<!--// f-right -->
			<div class="f-right m-f-right mgl">
				<h3>FAMILY SITE</h3>
				<div class="f-site">
					<a href="#toggle" data-target="#family" class="jsToggle">SELECT<span></span></a>
					<div class="family-site" id="family">
						<ul>
							<li><a href="http://www.xxio.jp/" target="_blank">XXIO JPN</a></li>
							<li><a href="http://www.xxiousa.com/" target="_blank">XXIO USA</a></li>
						</ul>
						<ul>
							<li><a href="http://golf.dunlop.co.jp/" target="_blank">GOLF JPN</a></li>
							<li><a href="http://www.srixon.com/" target="_blank">GOLF GBR</a></li>
							<!-- <li><a href="http://srixon-china.com/" target="_blank">GOLF CHN</a></li> -->
						</ul>
						<ul>
							<li><a href="http://cafe.naver.com/dunlopracquet" target="_blank">TENNIS KOR</a></li>
							<li><a href="http://www.srixon-tennis.com/" target="_blank">TENNIS JPN</a></li>
							<li><a href="http://www.dunloptyre.co.kr/front/content/main/main.asp" target="_blank">TYRE GBR</a>
							</li>
							<li><a href="http://www.dunloptyres.com.au/" target="_blank">TYRE AUS</a></li>
							<li><a href="http://www.dunloptires.com/en-US/tires-home" target="_blank">TYRE CAN</a></li>
							<li><a href="http://www.dunloptyre.co.kr/front/content/main/main.asp" target="_blank">TYPE KOR</a>
							</li>
							<li><a href="http://tyre.dunlop.co.jp/" target="_blank">TYPE JPN</a></li>
							<li><a href="https://www.dunlop.eu/de_de/consumer-products.html" target="_blank">TYPE GER</a></li>
							<li><a href="https://www.dunlop.eu/de_de/consumer-products.html" target="_blank">TYPE USA</a></li>
						</ul>
						<ul>
							<li><a href="http://www.srigroup.co.jp/" target="_blank">SRI GROUP</a></li>
							<li><a href="http://www.dunlopsports.co.jp/" target="_blank">DUNLOP SPORTS</a></li>
						</ul>
					</div>
				</div>
				<dl>
					<dt>SRIXON</dt>
					<dd>
						<ul>
							<li><a href="http://www.srixon.co.kr/item/balls/list.do?im_num=12">BALLS</a></li>
							<li><a href="http://www.srixon.co.kr/item/balls/list.do?im_num=8">CLUBS</a></li>
							<li><a href="http://www.srixon.co.kr/item/accessories/main.do">ACCESSORIES</a></li>
							<li><a href="http://www.srixon.co.kr/tour/playerList.do?sp_tour=PGA">TOUR</a></li>
							<li><a href="http://www.srixon.co.kr/experience/performanceInfo.do">EXPERIENCE</a></li>
							<li><a href="http://www.srixon.co.kr/news/newsList.do">NEWS&amp;EVENT</a></li>
							<li><a href="http://www.srixon.co.kr/cs/as_reception.do">C/S</a></li>
						</ul>
					</dd>
				</dl>
				<dl>
					<dt>CUSTOMER SERVICE</dt>
					<dd>
						<p>02.3462.3960</p>
						<!-- <p><a href="mailto:srixonsportskorea@gmail.com">srixonsportskorea@gmail.com</a></p> -->
					</dd>
				</dl>
				<p class="f-umenu re-none"><a href="http://www.srixon.co.kr/util/brand.do">INTRODUCE</a></p>
				<p class="f-umenu re-none"><a href="http://www.srixon.co.kr/util/catalog.do">CATALOGUE</a></p>
				<div class="foot_sns mo_view">
					<h3 class="space">FOLLOW US</h3>
					<ul class="f-sns">
						<li><a href="https://www.facebook.com/Srixonkorea/" target="_blank">facebook</a></li>
						<li><a href="https://www.instagram.com/srixon_korea/" target="_blank">instagram</a></li>
						<li><a href="https://www.youtube.com/channel/UCqTO4tAGtAyRjLQcPm7Wb7A?nohtml5=False"
								target="_blank">youtube</a></li>
					</ul>
				</div>
				<div class="f-xxio">
					<a href="http://www.xxio.co.kr" target="_blank" class="f_xxio"><img
							src="https://www.srixon.co.kr/images/f_xxio_logo.png" alt=""></a>
					<a href="http://www.clevelandgolf.co.kr/" target="_blank" class="f_cleve"><img
							src="https://www.srixon.co.kr/images/f_cleve_logo.png" alt=""></a>
				</div>
				<div class="f_awrad">
					<a href="http://www.i-award.or.kr/Web/" target="_blank" class="f_awrad"><img
							src="https://www.srixon.co.kr/images/foot_award.png" alt="" class="pc_view"></a>
					<a href="http://www.xxio.co.kr" target="_blank" class="f_awrad"><img
							src="https://www.srixon.co.kr/images/m_foot_award.png" alt="" class="mo_view"></a>
				</div>

				<p class="copy">COPYRIGHT &copy; 2018 BY DUNLOP SPORTS KOREA.<br> ALL RIGHTS RESERVED.</p>
			</div>
			<!--// f-right -->
		</div>
		<!--// f-right-cont -->
		<p class="btn-sc-top"><a href="#"><img src="https://www.srixon.co.kr/images/btn-top.png" alt="top"></a></p>
	</div>
	<!--// footer-inner -->
	<script type="text/javascript">
		$(function () {
			$('.btn-sc-top').on('click', function (e) {
				e.preventDefault();
				$('body, html').animate({
					scrollTop: 0
				}, '500');
			})
			noticeList();
			gnbList('7', 'balls', '#itemBalls');
			gnbList('8', 'clubs', '#itemClubs');
			gnbList('9', 'accessories', '#itemAccessories');
		});

		function noticeList() {
			$.ajax({
				url: '/news/ajaxNewsList.do',
				data: "",
				dataType: 'json',
				type: 'GET',
				error: function (xhr, status, e) {
					/* alert('처리중 문제가 발생하였습니다.\n관리자에게 문의하세요.\n에러메시지 : ' + e); */
				},
				success: function (data) {

					$(data.list).each(function (index, obj) {
						var title = obj.brd_title;
						var brd_num = obj.brd_num;
						var brd_gongji_flag = obj.brd_gongji_flag;

						if (title.length > 30) {
							title += "..";
						}
						$("#notice ul").append("<li><a href=\"http://www.srixon.co.kr/news/newsView.do?brd_num=" +
							brd_num + "&brd_gongji_flag=0\">" + title + "</a></li>");
					});
				}
			});
		}

		function gnbList(ic, sheet, selector) {
			var ib = '3';
			var result = $.ajax({
				url: '/item/' + sheet + '/gnb.do?ib_num=' + ib + '&ic_num=' + ic,
				type: "POST",
				async: false,
				dataType: "html"
			});
			result.success(function (data) {
				$(selector).append(data);
			});
		}

		/* 회원가입 공통(정품등록빼고)*/
		function dunlop_join() {
			var frm = document.memberJoinForm;
			frm.target = "_blank";
			frm.action = "http://www.dunlopkorea.co.kr/member/step01.do";
			frm.method = "post";
			frm.submit();
		}
	</script>

	<script>
	</script>

	<!-- 리타겟팅 광고 위한 태그 Start -->
	<!-- 리타겟팅 광고 위한 태그 End -->

</footer>