<title>스릭슨</title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1">
	<!-- 	<meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> 
	<!-- <meta name="naver-site-verification" content="d22c5e08a7f603b4e3dae73fc6e7247374344841" /> -->

	<!-- <meta name="description" content="투어에서 입증된, 글로벌 골프 브랜드 스릭슨 "> -->
	<meta name="title" content="스릭슨">
	<meta name="keywords" content="www.srixon.co.kr 투어에서 입증된, 글로벌 골프 브랜드 스릭슨 ">
	<meta name="description" content="www.srixon.co.kr 투어에서 입증된, 글로벌 골프 브랜드 스릭슨 ">
	<meta property="og:title" content="스릭슨">
	<meta property="og:description" content="www.srixon.co.kr 투어에서 입증된, 글로벌 골프 브랜드 스릭슨 ">

	<meta property="og:type" content="website">
	<meta property="og:title" content="스릭슨">
	<meta property="og:description" content="www.srixon.co.kr 투어에서 입증된, 글로벌 골프 브랜드 스릭슨">
	<meta property="og:image" content="http://www.srixon.co.kr/srx.jpg">
	<meta property="og:url" content="http://www.srixon.co.kr">

	<link rel="stylesheet" type="text/css" href="https://www.srixon.co.kr/common/css/base.css">
	<link rel="stylesheet" type="text/css" href="./common/css/style_new.css">
	<link rel="shortcut icon" type="image/x-icon" href="//www.srixon.co.kr/images/srix_zkQ_icon.ico" />

	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/jquery-1.9.1.min.js"></script>
	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/jquery.bpopup.min.js"></script>
	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/common.js?201809192"></script>
	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/jquery.plugin.js"></script>
	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/lib.js"></script>
	<script src="//cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

	<script type="text/javascript" src="https://www.srixon.co.kr/common/js/placeholders.min.js"></script>
	<!--[if lt IE 9]>
		<script src="https://www.srixon.co.kr/common/js/html5.js"></script>
	<![endif]-->
	<!-- 페이스북 픽셀작업 Start -->
	<!-- 페이스북 픽셀작업 End -->
	<script>
		if ($(window).width() < 600) {
			if (location.href.indexOf('brave-championship.do') != -1) {
				location.replace("brave-championship-m.do");
			}
		}
	</script>
	<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
	<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
	<style type='text/css'>
		@font-face {
			font-family: 'Verlag-Black';
			src: url('https://www.srixon.co.kr/images/brave/font/Verlag-Black.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/Verlag-Black.woff') format('woff');
			font-style: normal;
		}
		@font-face {
			font-family: 'Verlag-Book';
			src: url('https://www.srixon.co.kr/images/brave/font/Verlag-Book.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/Verlag-Book.woff') format('woff');
			font-style: normal;
		}
		@font-face {
			font-family: 'Hg99';
			src: url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP99gA.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP99gA.woff') format('woff');
			font-weight: normal;
			font-style: normal;
		}
		@font-face {
			font-family: 'Hg20';
			src: url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP20gA.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP20gA.woff') format('woff');
			font-weight: normal;
			font-style: normal;
		}
		@font-face {
			font-family: 'Hg40';
			src: url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP40gA.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP40gA.woff') format('woff');
			font-weight: normal;
			font-style: normal;
		}
		@font-face {
			font-family: 'Hg60';
			src: url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP60gA.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP60gA.woff') format('woff');
			font-weight: normal;
			font-style: normal;
		}
		@font-face {
			font-family: 'Hg80';
			src: url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP80gA.woff2') format('woff2'),
				url('https://www.srixon.co.kr/images/brave/font/HGGGothicssiP80gA.woff') format('woff');
			font-weight: normal;
			font-style: normal;
		}
		.content_box {
			position: relative;
			margin-top: 120px;
			background-color: #000000;
		}
		.wrap {
			width: 100%;
			text-align: center;
			position: relative;
			margin: 0;
			padding: 0;
		}
		/* .wrap img { max-width: 100%; min-width:1280px; height: auto;  } */
		.wrap img { max-width: 100%; height: auto; }
		.right_ani {
			position: absolute;
			right: -40%;
			display: none;
			top: 0;
			z-index: 9999;
			width: 100%;
		}
		.right_ani img {
			max-width: 100%;
			min-width: 1280px;
			height: auto;
		}
		.left_ani {
			position: absolute;
			left: -40%;
			display: none;
			top: 0;
			z-index: 9999;
			width: 100%;
		}
		.left_ani img {
			max-width: 100%;
			min-width: 1280px;
			height: auto;
		}

		footer#footer .footer-inner { max-width: 960px; }
		.main-visual-container {
			position: relative;
			min-width: 1012px;
			width: 100%;
			line-height: 0;
		}
		.main-visual-container .main-arrow {
			content: '';
			display: none;
			position: absolute;
			width: 92px;
			height: 51px;
			left: 50%;
			margin-left: -20px;
			background: url("https://www.srixon.co.kr/images/brave/arrow_down.png") 0 0 no-repeat;
		}
		.main-visual-container .img {
			width: 100%;
			position: absolute;
			top: 50%;
			-webkit-transform: translate(0, -50%);
			transform: translate(0, -50%);
		}
		.main-visual-container .visual-img1 { width: 100%; }

		.bxslider { display: none; }
		.bxslider2 { display: none; }
		.wrapbox { width: 1012px; margin: 0 auto; }
	</style>